## Import necessary librabraies

In [1]:
import pandas as pd

## 2. import data

In [2]:
height_pred = pd.read_csv("weight-height.csv")
height_pred

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

### 3. data Understanding

In [3]:
height_pred.shape

(10000, 3)

In [4]:
height_pred.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [7]:
height_pred.dtypes

Gender     object
Height    float64
Weight    float64
dtype: object

### 4. Data Preparation

### Lets do Feature Engineering 

* it is nothing but a concept of whatever you do with Features, we call it as Feature Engineering

* - Feature Deletion
  - feature Addition
  - Feature Selection
  - Feature Decomposition
  - feature transformation

###  we are interseted to converts units of height from Inches to CM and weight from pounds to Kilograms(Kg)

In [10]:
height_pred_copy = height_pred.copy()

In [11]:
del height_pred_copy['Gender']

In [12]:
height_pred_copy

         Height      Weight
0     73.847017  241.893563
1     68.781904  162.310473
2     74.110105  212.740856
3     71.730978  220.042470
4     69.881796  206.349801
...         ...         ...
9995  66.172652  136.777454
9996  67.067155  170.867906
9997  63.867992  128.475319
9998  69.034243  163.852461
9999  61.944246  113.649103

[10000 rows x 2 columns]

In [13]:
height_pred_copy['height_cm'] = height_pred_copy['Height']*2.54

In [15]:
height_pred_copy['weight_kg']= height_pred_copy['Weight']/2.205

In [16]:
height_pred_copy

         Height      Weight   height_cm   weight_kg
0     73.847017  241.893563  187.571423  109.702296
1     68.781904  162.310473  174.706036   73.610192
2     74.110105  212.740856  188.239668   96.481114
3     71.730978  220.042470  182.196685   99.792504
4     69.881796  206.349801  177.499761   93.582676
...         ...         ...         ...         ...
9995  66.172652  136.777454  168.078536   62.030591
9996  67.067155  170.867906  170.350573   77.491114
9997  63.867992  128.475319  162.224700   58.265451
9998  69.034243  163.852461  175.346978   74.309506
9999  61.944246  113.649103  157.338385   51.541543

[10000 rows x 4 columns]

In [17]:
height_pred_copy.drop(['Height','Weight'],axis = 1,inplace =True)

In [18]:
height_pred_copy

       height_cm   weight_kg
0     187.571423  109.702296
1     174.706036   73.610192
2     188.239668   96.481114
3     182.196685   99.792504
4     177.499761   93.582676
...          ...         ...
9995  168.078536   62.030591
9996  170.350573   77.491114
9997  162.224700   58.265451
9998  175.346978   74.309506
9999  157.338385   51.541543

[10000 rows x 2 columns]